import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class HeadphonesService {

  constructor() { }
  getHeadphones(){
    return [
      {
        img:"https://static.wixstatic.com/media/9c608a_1a0f12c2b7d44080a23e2642cae13b74.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/9c608a_1a0f12c2b7d44080a23e2642cae13b74.jpg",
        title:"JBL Quantum200",
        price:"19.99",
        price1:"19.99$",
        quantityTxt:"quantity",
        cart:"Add to cart",
        buy:"Buy Now",
        shipping:"Shipping",
        text1:"I'm a shipping policy. I'm a great place to add more information about your",
        text2:"shipping methods, packaging and cost. Providing straightforward",
        text3:"information about your shipping policy is a great way to build trust and",
        text4:"reassure your customers that they can buy from you with confidence.",
        returns:"Returns",
        returntxt1:"I'm a Return and Refund policy. I'm a great place to let your customers know",
        returntxt2:"what to do in case they are dissatisfied with their purchase. Having a",
        returntxt3:"straightforward refund or exchange policy is a great way to build trust and",
        returntxt4:"reassure your customers that they can buy with confidence.",
        description1:"I'm a product description. I'm a great place to include more information about your product. ",
        description2:"Buyers like to know what they're getting before they purchase.",
        headphones:"Headphones"
      },
      {
        img:"https://static.wixstatic.com/media/9c608a_8ac1adb0a50749a5aa72cd0181945cd0.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/9c608a_8ac1adb0a50749a5aa72cd0181945cd0.jpg",
        title:"JBL Tune",
        price:"29",
        quantityTxt:"quantity",
        cart:"Add to cart",
        buy:"Buy Now",
        shipping:"Shipping",
        text1:"I'm a shipping policy. I'm a great place to add more information about your",
        text2:"shipping methods, packaging and cost. Providing straightforward",
        text3:"information about your shipping policy is a great way to build trust and",
        text4:"reassure your customers that they can buy from you with confidence.",
        returns:"Returns",
        returntxt1:"I'm a Return and Refund policy. I'm a great place to let your customers know",
        returntxt2:"what to do in case they are dissatisfied with their purchase. Having a",
        returntxt3:"straightforward refund or exchange policy is a great way to build trust and",
        returntxt4:"reassure your customers that they can buy with confidence.",
        description1:"I'm a product description. I'm a great place to include more information about your product. ",
        description2:"Buyers like to know what they're getting before they purchase.",
        headphones:"Headphones"
      },
      {
        img:"https://static.wixstatic.com/media/9c608a_8db6307d7c7b4b70b675a59fd036787e.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/9c608a_8db6307d7c7b4b70b675a59fd036787e.jpg",
        title:"Asus Gaming",
        price:"589",
        quantityTxt:"quantity",
        qnt:1,
        cart:"Add to cart",
        buy:"Buy Now",
        shipping:"Shipping",
        text1:"I'm a shipping policy. I'm a great place to add more information about your",
        text2:"shipping methods, packaging and cost. Providing straightforward",
        text3:"information about your shipping policy is a great way to build trust and",
        text4:"reassure your customers that they can buy from you with confidence.",
        returns:"Returns",
        returntxt1:"I'm a Return and Refund policy. I'm a great place to let your customers know",
        returntxt2:"what to do in case they are dissatisfied with their purchase. Having a",
        returntxt3:"straightforward refund or exchange policy is a great way to build trust and",
        returntxt4:"reassure your customers that they can buy with confidence.",
        description1:"I'm a product description. I'm a great place to include more information about your product. ",
        description2:"Buyers like to know what they're getting before they purchase.",
        headphones:"Headphones"
      },
      {
        img:"https://static.wixstatic.com/media/9c608a_a220b0ace7c14f89b580dceded35f7b6.jpg/v1/fill/w_500,h_500,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/9c608a_a220b0ace7c14f89b580dceded35f7b6.jpg",
        title:"JBL JR",
        price:"100",
        quantityTxt:"quantity",
        qnt:1,
        cart:"Add to cart",
        buy:"Buy Now",
        shipping:"Shipping",
        text1:"I'm a shipping policy. I'm a great place to add more information about your",
        text2:"shipping methods, packaging and cost. Providing straightforward",
        text3:"information about your shipping policy is a great way to build trust and",
        text4:"reassure your customers that they can buy from you with confidence.",
        returns:"Returns",
        returntxt1:"I'm a Return and Refund policy. I'm a great place to let your customers know",
        returntxt2:"what to do in case they are dissatisfied with their purchase. Having a",
        returntxt3:"straightforward refund or exchange policy is a great way to build trust and",
        returntxt4:"reassure your customers that they can buy with confidence.",
        description1:"I'm a product description. I'm a great place to include more information about your product. ",
        description2:"Buyers like to know what they're getting before they purchase.",
        headphones:"Headphones"
      },
      {
        img:"https://m.media-amazon.com/images/I/41V2awCLZHL._SS400_.jpg",
        title:"Razer",
        price:"200",
        quantityTxt:"quantity",
        qnt:1,
        cart:"Add to cart",
        buy:"Buy Now",
        shipping:"Shipping",
        text1:"I'm a shipping policy. I'm a great place to add more information about your",
        text2:"shipping methods, packaging and cost. Providing straightforward",
        text3:"information about your shipping policy is a great way to build trust and",
        text4:"reassure your customers that they can buy from you with confidence.",
        returns:"Returns",
        returntxt1:"I'm a Return and Refund policy. I'm a great place to let your customers know",
        returntxt2:"what to do in case they are dissatisfied with their purchase. Having a",
        returntxt3:"straightforward refund or exchange policy is a great way to build trust and",
        returntxt4:"reassure your customers that they can buy with confidence.",
        description1:"I'm a product description. I'm a great place to include more information about your product. ",
        description2:"Buyers like to know what they're getting before they purchase.",
        headphones:"Headphones"
      },
      {
        img:"https://m.media-amazon.com/images/I/71FVW0VhgfL._AC_UF894,1000_QL80_.jpg",
        title:"JLAB",
        price:"350",
        qnt:1,
        quantityTxt:"quantity",
        cart:"Add to cart",
        buy:"Buy Now",
        shipping:"Shipping",
        text1:"I'm a shipping policy. I'm a great place to add more information about your",
        text2:"shipping methods, packaging and cost. Providing straightforward",
        text3:"information about your shipping policy is a great way to build trust and",
        text4:"reassure your customers that they can buy from you with confidence.",
        returns:"Returns",
        returntxt1:"I'm a Return and Refund policy. I'm a great place to let your customers know",
        returntxt2:"what to do in case they are dissatisfied with their purchase. Having a",
        returntxt3:"straightforward refund or exchange policy is a great way to build trust and",
        returntxt4:"reassure your customers that they can buy with confidence.",
        description1:"I'm a product description. I'm a great place to include more information about your product. ",
        description2:"Buyers like to know what they're getting before they purchase.",
        headphones:"Headphones"
      },
      {
        img:"https://m.media-amazon.com/images/I/412GIevRYuL._AC_.jpg",
        title:"HyperX Cloud",
        price:"123",
        quantityTxt:"quantity",
        qnt:1,
        cart:"Add to cart",
        buy:"Buy Now",
        shipping:"Shipping",
        text1:"I'm a shipping policy. I'm a great place to add more information about your",
        text2:"shipping methods, packaging and cost. Providing straightforward",
        text3:"information about your shipping policy is a great way to build trust and",
        text4:"reassure your customers that they can buy from you with confidence.",
        returns:"Returns",
        returntxt1:"I'm a Return and Refund policy. I'm a great place to let your customers know",
        returntxt2:"what to do in case they are dissatisfied with their purchase. Having a",
        returntxt3:"straightforward refund or exchange policy is a great way to build trust and",
        returntxt4:"reassure your customers that they can buy with confidence.",
        description1:"I'm a product description. I'm a great place to include more information about your product. ",
        description2:"Buyers like to know what they're getting before they purchase.",
        headphones:"Headphones"
      },
      {
        img:"https://i.ebayimg.com/images/g/7xoAAOSw14xjFAec/s-l1600.png",
        title:"Sony",
        price:"80",
        quantityTxt:"quantity",
        qnt:1,
        cart:"Add to cart",
        buy:"Buy Now",
        shipping:"Shipping",
        text1:"I'm a shipping policy. I'm a great place to add more information about your",
        text2:"shipping methods, packaging and cost. Providing straightforward",
        text3:"information about your shipping policy is a great way to build trust and",
        text4:"reassure your customers that they can buy from you with confidence.",
        returns:"Returns",
        returntxt1:"I'm a Return and Refund policy. I'm a great place to let your customers know",
        returntxt2:"what to do in case they are dissatisfied with their purchase. Having a",
        returntxt3:"straightforward refund or exchange policy is a great way to build trust and",
        returntxt4:"reassure your customers that they can buy with confidence.",
        description1:"I'm a product description. I'm a great place to include more information about your product. ",
        description2:"Buyers like to know what they're getting before they purchase.",
        headphones:"Headphones"
      }
    ]
  }

}
